## Pandas

In [1]:
import pandas as pd

In [2]:
cidades = [
    "São Paulo (SP)",
    "Rio de Janeiro (RJ)",
    "Brasília (DF)",
    "Fortaleza (CE)",
    "Salvador (BA)",
    "Belo Horizonte (MG)",
    "Manaus (AM)",
    "Curitiba (PR)",    
]

populacoes = [
    12,
    6.5,
    3,
    2.4,
    2.4,
    2.3,
    2,
    1.7    
]

In [9]:
cidades_serie = pd.Series(cidades)
cidades_serie

0         São Paulo (SP)
1    Rio de Janeiro (RJ)
2          Brasília (DF)
3         Fortaleza (CE)
4          Salvador (BA)
5    Belo Horizonte (MG)
6            Manaus (AM)
7          Curitiba (PR)
dtype: str

In [6]:
populacoes_serie = pd.Series(populacoes)
populacoes_serie

0    12.0
1     6.5
2     3.0
3     2.4
4     2.4
5     2.3
6     2.0
7     1.7
dtype: float64

In [10]:
cidades_serie[3]

'Fortaleza (CE)'

In [12]:
cidades_serie[3:6]

3         Fortaleza (CE)
4          Salvador (BA)
5    Belo Horizonte (MG)
dtype: str

In [13]:
populacoes_serie.max()

np.float64(12.0)

In [14]:
populacoes_serie.mean()

np.float64(4.0375)

In [15]:
populacoes_serie * 2

0    24.0
1    13.0
2     6.0
3     4.8
4     4.8
5     4.6
6     4.0
7     3.4
dtype: float64

## DataFrames

In [16]:
cidades_populosas = pd.DataFrame({'cidade': cidades_serie, 'populacao em milhoes': populacoes_serie})
cidades_populosas

                cidade  populacao em milhoes
0       São Paulo (SP)                  12.0
1  Rio de Janeiro (RJ)                   6.5
2        Brasília (DF)                   3.0
3       Fortaleza (CE)                   2.4
4        Salvador (BA)                   2.4
5  Belo Horizonte (MG)                   2.3
6          Manaus (AM)                   2.0
7        Curitiba (PR)                   1.7

In [17]:
cidades_populosas.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cidade                8 non-null      str
 1   populacao em milhoes  8 non-null      float64
dtypes: float64(1), str(1)
memory usage: 260.0 bytes

In [18]:
cidades_populosas['cidade']

0         São Paulo (SP)
1    Rio de Janeiro (RJ)
2          Brasília (DF)
3         Fortaleza (CE)
4          Salvador (BA)
5    Belo Horizonte (MG)
6            Manaus (AM)
7          Curitiba (PR)
Name: cidade, dtype: str

In [19]:
cidades_populosas.iloc[3]

cidade                  Fortaleza (CE)
populacao em milhoes               2.4
Name: 3, dtype: object

In [20]:
cidades_populosas.iloc[3:6]

                cidade  populacao em milhoes
3       Fortaleza (CE)                   2.4
4        Salvador (BA)                   2.4
5  Belo Horizonte (MG)                   2.3

In [22]:
cidades_populosas.head()

                cidade  populacao em milhoes
0       São Paulo (SP)                  12.0
1  Rio de Janeiro (RJ)                   6.5
2        Brasília (DF)                   3.0
3       Fortaleza (CE)                   2.4
4        Salvador (BA)                   2.4

In [23]:
cidades_populosas.tail()

                cidade  populacao em milhoes
3       Fortaleza (CE)                   2.4
4        Salvador (BA)                   2.4
5  Belo Horizonte (MG)                   2.3
6          Manaus (AM)                   2.0
7        Curitiba (PR)                   1.7

In [26]:
cidades_populosas['populacao em milhoes'].mean()

np.float64(4.0375)

In [27]:
area_urbana = [
    '914',
    '640',
    '590',
    '253',
    '196',
    '274',
    '277',
    '336'
]

In [28]:
cidades_populosas['area urbana em km²'] = area_urbana
cidades_populosas

                cidade  populacao em milhoes area urbana em km²
0       São Paulo (SP)                  12.0                914
1  Rio de Janeiro (RJ)                   6.5                640
2        Brasília (DF)                   3.0                590
3       Fortaleza (CE)                   2.4                253
4        Salvador (BA)                   2.4                196
5  Belo Horizonte (MG)                   2.3                274
6          Manaus (AM)                   2.0                277
7        Curitiba (PR)                   1.7                336

## Aplicando Funções

In [29]:
cidades_populosas['populaca'] = cidades_populosas['populacao em milhoes'] * 1_000_000
cidades_populosas

                cidade  populacao em milhoes area urbana em km²    populaca
0       São Paulo (SP)                  12.0                914  12000000.0
1  Rio de Janeiro (RJ)                   6.5                640   6500000.0
2        Brasília (DF)                   3.0                590   3000000.0
3       Fortaleza (CE)                   2.4                253   2400000.0
4        Salvador (BA)                   2.4                196   2400000.0
5  Belo Horizonte (MG)                   2.3                274   2300000.0
6          Manaus (AM)                   2.0                277   2000000.0
7        Curitiba (PR)                   1.7                336   1700000.0

In [30]:
cidades_populosas.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cidade                8 non-null      str
 1   populacao em milhoes  8 non-null      float64
 2   area urbana em km²    8 non-null      str
 3   populaca              8 non-null      float64
dtypes: float64(2), str(2)
memory usage: 388.0 bytes

In [31]:
cidades_populosas['area urbana em km²'] = cidades_populosas['area urbana em km²'].astype(int)
cidades_populosas.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cidade                8 non-null      str
 1   populacao em milhoes  8 non-null      float64
 2   area urbana em km²    8 non-null      int64
 3   populaca              8 non-null      float64
dtypes: float64(2), int64(1), str(1)
memory usage: 388.0 bytes

## Combinando Dados de Colunas

In [42]:
cidades_populosas['habitantes por km²'] = cidades_populosas['populaca'] / cidades_populosas['area urbana em km²']
cidades_populosas

,cidade,populacao em milhoes,area urbana em km²,populaca,habitantes por km²
0,São Paulo (SP),12.0,914,12000000.0,13129.102845
1,Rio de Janeiro (RJ),6.5,640,6500000.0,10156.250000
2,Brasília (DF),3.0,590,3000000.0,5084.745763
3,Fortaleza (CE),2.4,253,2400000.0,9486.166008
4,Salvador (BA),2.4,196,2400000.0,12244.897959
5,Belo Horizonte (MG),2.3,274,2300000.0,8394.160584
6,Manaus (AM),2.0,277,2000000.0,7220.216606
7,Curitiba (PR),1.7,336,1700000.0,5059.523810

In [51]:
import pandas as pd

A = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
B = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
C = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
D = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
E = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
F = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
G = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
H = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

acentos_serie = pd.Series(A)
acentos1_serie = pd.Series(B)
acentos2_serie = pd.Series(C)
acentos3_serie = pd.Series(D)
acentos4_serie = pd.Series(E)
acentos5_serie = pd.Series(F)
acentos6_serie = pd.Series(G)
acentos7_serie = pd.Series(H)

sala_cinema = pd.DataFrame({'A': acentos_serie,'B': acentos1_serie,'C': acentos2_serie,'D': acentos3_serie,'E': acentos4_serie,'F': acentos5_serie,'G': acentos6_serie,'H': acentos7_serie,})
sala_cinema

ModuleNotFoundError: No module named 'DataFrame'

In [55]:
sala_cinema ["F"][8]

np.int64(9)