# Lidando com Dados Faltantes

##### Imagine fazer uma análise para prever o preço de casas, faltando o número de quartos em alguns exemplos de dados. A análise levaria a resultados imprecisos e consequentemente a decisões erradas. Neste notebook veremos como lidar com dados faltantes em um conjunto de dados da área da saúde.

In [2]:
import pandas as pd

### Carregando os Dados

In [51]:
diabetes = pd.read_excel('diabetes.xlsx')

In [52]:
diabetes

,pressao arterial,concentraçao de glicose,insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,NaN,A,50,33.6,S
1,66.0,85.0,NaN,O,31,26.6,N
2,64.0,183.0,NaN,A,32,23.3,S
3,66.0,89.0,94.0,A,21,28.1,N
4,40.0,137.0,168.0,O,33,43.1,S
...,...,...,...,...,...,...,...
763,76.0,101.0,180.0,A,63,32.9,N
764,70.0,122.0,NaN,A,27,36.8,N
765,72.0,121.0,112.0,O,30,26.2,N
766,60.0,126.0,NaN,NaN,47,30.1,S
767,70.0,93.0,NaN,A,23,30.4,N

In [53]:
diabetes.to_csv('diabetes.csv', index=False)

In [54]:
diabetes = pd.read_csv('diabetes.csv')

In [55]:
diabetes

,pressao arterial,concentraçao de glicose,insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,NaN,A,50,33.6,S
1,66.0,85.0,NaN,O,31,26.6,N
2,64.0,183.0,NaN,A,32,23.3,S
3,66.0,89.0,94.0,A,21,28.1,N
4,40.0,137.0,168.0,O,33,43.1,S
...,...,...,...,...,...,...,...
763,76.0,101.0,180.0,A,63,32.9,N
764,70.0,122.0,NaN,A,27,36.8,N
765,72.0,121.0,112.0,O,30,26.2,N
766,60.0,126.0,NaN,NaN,47,30.1,S
767,70.0,93.0,NaN,A,23,30.4,N

In [56]:
diabetes.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pressao arterial         733 non-null    float64
 1   concentraçao de glicose  763 non-null    float64
 2   insulina                 394 non-null    float64
 3   tipo sanguineo           723 non-null    str
 4   idade                    768 non-null    int64
 5   imc                      757 non-null    float64
 6   diabetico                768 non-null    str
dtypes: float64(4), int64(1), str(2)
memory usage: 42.1 KB

In [57]:
diabetes.head()

,pressao arterial,concentraçao de glicose,insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,NaN,A,50,33.6,S
1,66.0,85.0,NaN,O,31,26.6,N
2,64.0,183.0,NaN,A,32,23.3,S
3,66.0,89.0,94.0,A,21,28.1,N
4,40.0,137.0,168.0,O,33,43.1,S

In [58]:
diabetes.tail()

,pressao arterial,concentraçao de glicose,insulina,tipo sanguineo,idade,imc,diabetico
763,76.0,101.0,180.0,A,63,32.9,N
764,70.0,122.0,NaN,A,27,36.8,N
765,72.0,121.0,112.0,O,30,26.2,N
766,60.0,126.0,NaN,NaN,47,30.1,S
767,70.0,93.0,NaN,A,23,30.4,N

In [59]:
diabetes.isna().sum()

pressao arterial            35
concentraçao de glicose      5
insulina                   374
tipo sanguineo              45
idade                        0
imc                         11
diabetico                    0
dtype: int64

In [60]:
diabetes['diabetico'].value_counts()

diabetico
N    500
S    268
Name: count, dtype: int64

In [61]:
diabetes[diabetes['concentraçao de glicose'].isna() | diabetes['imc'].isna()]

,pressao arterial,concentraçao de glicose,insulina,tipo sanguineo,idade,imc,diabetico
9,96.0,125.0,NaN,A,54,NaN,S
49,NaN,105.0,NaN,A,24,NaN,N
60,NaN,84.0,NaN,NaN,21,NaN,N
75,48.0,NaN,NaN,A,22,24.7,N
81,NaN,74.0,NaN,A,22,NaN,N
145,75.0,102.0,NaN,A,21,NaN,N
182,74.0,NaN,23.0,O,21,27.7,N
342,68.0,NaN,NaN,A,22,32.0,N
349,80.0,NaN,NaN,O,37,41.0,S
371,64.0,118.0,89.0,O,21,NaN,N
426,NaN,94.0,NaN,B,25,NaN,N
494,NaN,80.0,NaN,B,22,NaN,N
502,68.0,NaN,NaN,O,41,39.0,S
522,NaN,114.0,NaN,NaN,26,NaN,N
684,82.0,136.0,NaN,B,69,NaN,N
706,NaN,115.0,NaN,O,30,NaN,S

In [66]:
diabetes.dropna(axis='index', subset=['concentraçao de glicose', 'imc'], inplace=True)

In [67]:
diabetes.info()

<class 'pandas.DataFrame'>
Index: 752 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pressao arterial         724 non-null    float64
 1   concentraçao de glicose  752 non-null    float64
 2   insulina                 392 non-null    float64
 3   tipo sanguineo           709 non-null    str
 4   idade                    752 non-null    int64
 5   imc                      752 non-null    float64
 6   diabetico                752 non-null    str
dtypes: float64(4), int64(1), str(2)
memory usage: 47.0 KB

## Substituindo Valores

In [68]:
diabetes.isna().sum()

pressao arterial            28
concentraçao de glicose      0
insulina                   360
tipo sanguineo              43
idade                        0
imc                          0
diabetico                    0
dtype: int64

In [69]:
diabetes[diabetes['insulina'].isna()].head(20)

,pressao arterial,concentraçao de glicose,insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,NaN,A,50,33.6,S
1,66.0,85.0,NaN,O,31,26.6,N
2,64.0,183.0,NaN,A,32,23.3,S
5,74.0,116.0,NaN,A,30,25.6,N
7,NaN,115.0,NaN,A,29,35.3,N
10,92.0,110.0,NaN,O,30,37.6,N
11,74.0,168.0,NaN,NaN,34,38.0,S
12,80.0,139.0,NaN,O,57,27.1,N
15,NaN,100.0,NaN,AB,32,30.0,S
17,74.0,107.0,NaN,AB,31,29.6,S
21,84.0,99.0,NaN,O,50,35.4,N
22,90.0,196.0,NaN,A,41,39.8,S
23,80.0,119.0,NaN,O,29,29.0,S
26,76.0,147.0,NaN,AB,43,39.4,S
29,92.0,117.0,NaN,O,38,34.1,N
30,75.0,109.0,NaN,A,60,36.0,N
33,92.0,92.0,NaN,A,28,19.9,N
34,78.0,122.0,NaN,A,45,27.6,N
36,76.0,138.0,NaN,A,35,33.2,N
37,76.0,102.0,NaN,O,46,32.9,S

In [71]:
diabetes['leu insulina'] = ~diabetes ['insulina'].isna()
diabetes

,pressao arterial,concentraçao de glicose,insulina,tipo sanguineo,idade,imc,diabetico,leu insulina
0,72.0,148.0,NaN,A,50,33.6,S,False
1,66.0,85.0,NaN,O,31,26.6,N,False
2,64.0,183.0,NaN,A,32,23.3,S,False
3,66.0,89.0,94.0,A,21,28.1,N,True
4,40.0,137.0,168.0,O,33,43.1,S,True
...,...,...,...,...,...,...,...,...
763,76.0,101.0,180.0,A,63,32.9,N,True
764,70.0,122.0,NaN,A,27,36.8,N,False
765,72.0,121.0,112.0,O,30,26.2,N,True
766,60.0,126.0,NaN,NaN,47,30.1,S,False
767,70.0,93.0,NaN,A,23,30.4,N,False

In [72]:
diabetes.drop(columns=['insulina'], inplace=True)
diabetes

,pressao arterial,concentraçao de glicose,tipo sanguineo,idade,imc,diabetico,leu insulina
0,72.0,148.0,A,50,33.6,S,False
1,66.0,85.0,O,31,26.6,N,False
2,64.0,183.0,A,32,23.3,S,False
3,66.0,89.0,A,21,28.1,N,True
4,40.0,137.0,O,33,43.1,S,True
...,...,...,...,...,...,...,...
763,76.0,101.0,A,63,32.9,N,True
764,70.0,122.0,A,27,36.8,N,False
765,72.0,121.0,O,30,26.2,N,True
766,60.0,126.0,NaN,47,30.1,S,False
767,70.0,93.0,A,23,30.4,N,False

In [73]:
diabetes = diabetes[[
    'pressao arterial',
    'concentraçao de glicose',
    'leu insulina',
    'tipo sanguineo',
    'idade',
    'imc',
    'diabetico'
]]
diabetes

,pressao arterial,concentraçao de glicose,leu insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,False,A,50,33.6,S
1,66.0,85.0,False,O,31,26.6,N
2,64.0,183.0,False,A,32,23.3,S
3,66.0,89.0,True,A,21,28.1,N
4,40.0,137.0,True,O,33,43.1,S
...,...,...,...,...,...,...,...
763,76.0,101.0,True,A,63,32.9,N
764,70.0,122.0,False,A,27,36.8,N
765,72.0,121.0,True,O,30,26.2,N
766,60.0,126.0,False,NaN,47,30.1,S
767,70.0,93.0,False,A,23,30.4,N

In [74]:
diabetes.info()

<class 'pandas.DataFrame'>
Index: 752 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pressao arterial         724 non-null    float64
 1   concentraçao de glicose  752 non-null    float64
 2   leu insulina             752 non-null    bool
 3   tipo sanguineo           709 non-null    str
 4   idade                    752 non-null    int64
 5   imc                      752 non-null    float64
 6   diabetico                752 non-null    str
dtypes: bool(1), float64(3), int64(1), str(2)
memory usage: 41.9 KB

## Preenchendo Valores

In [75]:
diabetes.isna().sum()

pressao arterial           28
concentraçao de glicose     0
leu insulina                0
tipo sanguineo             43
idade                       0
imc                         0
diabetico                   0
dtype: int64

In [76]:
diabetes['pressao arterial']

0      72.0
1      66.0
2      64.0
3      66.0
4      40.0
       ...
763    76.0
764    70.0
765    72.0
766    60.0
767    70.0
Name: pressao arterial, Length: 752, dtype: float64

In [77]:
diabetes['tipo sanguineo']

0        A
1        O
2        A
3        A
4        O
      ...
763      A
764      A
765      O
766    NaN
767      A
Name: tipo sanguineo, Length: 752, dtype: str

In [78]:
diabetes['pressao arterial'].describe()

count    724.000000
mean      72.400552
std       12.379870
min       24.000000
25%       64.000000
50%       72.000000
75%       80.000000
max      122.000000
Name: pressao arterial, dtype: float64

In [79]:
diabetes['tipo sanguineo'].value_counts()

tipo sanguineo
A     390
O     223
B      75
AB     21
Name: count, dtype: int64

In [88]:
diabetes.fillna({'pressao arterial': 72.4, 'tipo sanguineo': 'A'}, inplace=True)

,pressao arterial,concentraçao de glicose,leu insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,False,A,50,33.6,S
1,66.0,85.0,False,O,31,26.6,N
2,64.0,183.0,False,A,32,23.3,S
3,66.0,89.0,True,A,21,28.1,N
4,40.0,137.0,True,O,33,43.1,S
...,...,...,...,...,...,...,...
763,76.0,101.0,True,A,63,32.9,N
764,70.0,122.0,False,A,27,36.8,N
765,72.0,121.0,True,O,30,26.2,N
766,60.0,126.0,False,A,47,30.1,S
767,70.0,93.0,False,A,23,30.4,N

In [89]:
diabetes.info()

<class 'pandas.DataFrame'>
Index: 752 entries, 0 to 767
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pressao arterial         752 non-null    float64
 1   concentraçao de glicose  752 non-null    float64
 2   leu insulina             752 non-null    bool
 3   tipo sanguineo           752 non-null    str
 4   idade                    752 non-null    int64
 5   imc                      752 non-null    float64
 6   diabetico                752 non-null    str
dtypes: bool(1), float64(3), int64(1), str(2)
memory usage: 41.9 KB

In [90]:
diabetes.isna().sum()

pressao arterial           0
concentraçao de glicose    0
leu insulina               0
tipo sanguineo             0
idade                      0
imc                        0
diabetico                  0
dtype: int64

In [91]:
diabetes

,pressao arterial,concentraçao de glicose,leu insulina,tipo sanguineo,idade,imc,diabetico
0,72.0,148.0,False,A,50,33.6,S
1,66.0,85.0,False,O,31,26.6,N
2,64.0,183.0,False,A,32,23.3,S
3,66.0,89.0,True,A,21,28.1,N
4,40.0,137.0,True,O,33,43.1,S
...,...,...,...,...,...,...,...
763,76.0,101.0,True,A,63,32.9,N
764,70.0,122.0,False,A,27,36.8,N
765,72.0,121.0,True,O,30,26.2,N
766,60.0,126.0,False,A,47,30.1,S
767,70.0,93.0,False,A,23,30.4,N