# Exercício Guiado: Calcular medias de tendência central e dispersão com Pandas

<p> Realizar uma analise das medidas estatisticas no conjunto de dados de cidades brasileiras com mais de 100 mil habitantes
    Deve primeiro remover as cidades com números extremos do conjunto usando a medida de Desvio Padrão, depois calcular a Media
    e Mediana da População nestas cidades, e a Moda de Uniões Federativas presentes.
</p>

In [42]:
import pandas as pd

### Leitura dos Dados

In [52]:
dados = pd.read_html('python-diferentes-formatos-dados/cidades.html', encoding='utf-8')

In [53]:
dados

[     ranking       municipio                uf   populacao
 0          1       São Paulo         São Paulo  11 451 999
 1          2  Rio de Janeiro    Rio de Janeiro   6 211 223
 2          3        Brasília  Distrito Federal   2 817 381
 3          4       Fortaleza             Ceará   2 428 708
 4          5        Salvador             Bahia   2 417 678
 ..       ...             ...               ...         ...
 314      315      Manacapuru          Amazonas     101 883
 315      316          Balsas          Maranhão     101 767
 316      317         Lagarto           Sergipe     101 579
 317      318           Assis         São Paulo     101 409
 318      319       Itaperuna    Rio de Janeiro     101 041

 [319 rows x 4 columns]]

In [54]:
dados_populacao = dados[0]
dados_populacao

     ranking       municipio                uf   populacao
0          1       São Paulo         São Paulo  11 451 999
1          2  Rio de Janeiro    Rio de Janeiro   6 211 223
2          3        Brasília  Distrito Federal   2 817 381
3          4       Fortaleza             Ceará   2 428 708
4          5        Salvador             Bahia   2 417 678
..       ...             ...               ...         ...
314      315      Manacapuru          Amazonas     101 883
315      316          Balsas          Maranhão     101 767
316      317         Lagarto           Sergipe     101 579
317      318           Assis         São Paulo     101 409
318      319       Itaperuna    Rio de Janeiro     101 041

[319 rows x 4 columns]

In [73]:
dados.iloc[(dados['ranking'] < 20) | (dados['uf'] == 'São Paulo')]
dados

AttributeError: 'list' object has no attribute 'iloc'

In [55]:
dados_populacao.columns = ['ranking', 'municipio', 'uf', 'populacao']
dados_populacao

     ranking       municipio                uf   populacao
0          1       São Paulo         São Paulo  11 451 999
1          2  Rio de Janeiro    Rio de Janeiro   6 211 223
2          3        Brasília  Distrito Federal   2 817 381
3          4       Fortaleza             Ceará   2 428 708
4          5        Salvador             Bahia   2 417 678
..       ...             ...               ...         ...
314      315      Manacapuru          Amazonas     101 883
315      316          Balsas          Maranhão     101 767
316      317         Lagarto           Sergipe     101 579
317      318           Assis         São Paulo     101 409
318      319       Itaperuna    Rio de Janeiro     101 041

[319 rows x 4 columns]

In [75]:
dados_populacao.iloc[(dados_populacao['ranking'] < 20) | (dados_populacao['uf'] == 'São Paulo')]
dados_populacao

     ranking       municipio                uf  populacao  dentro_da_faixa
0          1       São Paulo         São Paulo   11451999            False
1          2  Rio de Janeiro    Rio de Janeiro    6211223            False
2          3        Brasília  Distrito Federal    2817381            False
3          4       Fortaleza             Ceará    2428708            False
4          5        Salvador             Bahia    2417678            False
..       ...             ...               ...        ...              ...
314      315      Manacapuru          Amazonas     101883             True
315      316          Balsas          Maranhão     101767             True
316      317         Lagarto           Sergipe     101579             True
317      318           Assis         São Paulo     101409             True
318      319       Itaperuna    Rio de Janeiro     101041             True

[319 rows x 5 columns]

In [56]:
dados_populacao[:20]

    ranking       municipio                  uf   populacao
0         1       São Paulo           São Paulo  11 451 999
1         2  Rio de Janeiro      Rio de Janeiro   6 211 223
2         3        Brasília    Distrito Federal   2 817 381
3         4       Fortaleza               Ceará   2 428 708
4         5        Salvador               Bahia   2 417 678
5         6  Belo Horizonte        Minas Gerais   2 315 560
6         7          Manaus            Amazonas   2 063 689
7         8        Curitiba              Paraná   1 773 718
8         9          Recife          Pernambuco   1 488 920
9        10         Goiânia               Goiás   1 437 366
10       11    Porto Alegre   Rio Grande do Sul   1 332 845
11       12           Belém                Pará   1 303 403
12       13       Guarulhos           São Paulo   1 291 771
13       14        Campinas           São Paulo   1 139 047
14       15        São Luís            Maranhão   1 037 775
15       16          Maceió             Alagoas     957 916
16       17    Campo Grande  Mato Grosso do Sul     898 100
17       18     São Gonçalo      Rio de Janeiro     896 744
18       19        Teresina               Piauí     866 300
19       20     João Pessoa             Paraíba     833 932

In [57]:
dados_populacao.dtypes

ranking      int64
municipio      str
uf             str
populacao      str
dtype: object

In [59]:
dados_populacao['populacao'] = dados_populacao['populacao'].str.replace(r'\s', '', regex=True).astype(int)
dados_populacao

     ranking       municipio                uf  populacao
0          1       São Paulo         São Paulo   11451999
1          2  Rio de Janeiro    Rio de Janeiro    6211223
2          3        Brasília  Distrito Federal    2817381
3          4       Fortaleza             Ceará    2428708
4          5        Salvador             Bahia    2417678
..       ...             ...               ...        ...
314      315      Manacapuru          Amazonas     101883
315      316          Balsas          Maranhão     101767
316      317         Lagarto           Sergipe     101579
317      318           Assis         São Paulo     101409
318      319       Itaperuna    Rio de Janeiro     101041

[319 rows x 4 columns]

## Calculando o Desvio Padrão

In [61]:
media_total = dados_populacao['populacao'].mean()
mediana_total = dados_populacao['populacao'].median()

print(f'Media conjunto de dados completo: {media_total:,}\nMediana conjunto de dados completo: {mediana_total:,}')

Media conjunto de dados completo: 362,520.1724137931
Mediana conjunto de dados completo: 187,315.0

In [62]:
desvio_padrao = dados_populacao['populacao'].std()

print(f'Desvio Padrão conjunto de dados completo: {desvio_padrao:,}')

Desvio Padrão conjunto de dados completo: 792,866.9083592542

## Filtrando Valores Externos

In [65]:
limite_superior = media_total + 2*desvio_padrao
limite_inferior = media_total - 2*desvio_padrao

print(f'Serão excluídos os valores fora da faixa [{limite_inferior:,}, {limite_superior:,}]')

Serão excluídos os valores fora da faixa [-1,223,213.6443047153, 1,948,253.9891323016]

In [66]:
dados_populacao['dentro_da_faixa'] = dados_populacao['populacao'] <= limite_superior
dados_populacao

     ranking       municipio                uf  populacao  dentro_da_faixa
0          1       São Paulo         São Paulo   11451999            False
1          2  Rio de Janeiro    Rio de Janeiro    6211223            False
2          3        Brasília  Distrito Federal    2817381            False
3          4       Fortaleza             Ceará    2428708            False
4          5        Salvador             Bahia    2417678            False
..       ...             ...               ...        ...              ...
314      315      Manacapuru          Amazonas     101883             True
315      316          Balsas          Maranhão     101767             True
316      317         Lagarto           Sergipe     101579             True
317      318           Assis         São Paulo     101409             True
318      319       Itaperuna    Rio de Janeiro     101041             True

[319 rows x 5 columns]

In [67]:
dados_populacao_reduzido = dados_populacao[dados_populacao['dentro_da_faixa']]
dados_populacao_reduzido

     ranking     municipio                 uf  populacao  dentro_da_faixa
7          8      Curitiba             Paraná    1773718             True
8          9        Recife         Pernambuco    1488920             True
9         10       Goiânia              Goiás    1437366             True
10        11  Porto Alegre  Rio Grande do Sul    1332845             True
11        12         Belém               Pará    1303403             True
..       ...           ...                ...        ...              ...
314      315    Manacapuru           Amazonas     101883             True
315      316        Balsas           Maranhão     101767             True
316      317       Lagarto            Sergipe     101579             True
317      318         Assis          São Paulo     101409             True
318      319     Itaperuna     Rio de Janeiro     101041             True

[312 rows x 5 columns]

## Calculando Medidas para o novo Conjunto

In [68]:
media_reduzido = dados_populacao_reduzido['populacao'].mean()
mediana_reduzido = dados_populacao_reduzido['populacao'].median()

print(f'Media conjunto de dados reduzido: {media_reduzido:,}\nMediana conjunto de dados reduzido: {mediana_reduzido:,}')

Media conjunto de dados reduzido: 275,441.33653846156
Mediana conjunto de dados reduzido: 183,003.5

In [69]:
dados_populacao_reduzido['uf'].mode()

0    São Paulo
Name: uf, dtype: str

In [70]:
dados_populacao_reduzido['uf'].value_counts()

uf
São Paulo              77
Minas Gerais           33
Rio de Janeiro         27
Paraná                 22
Rio Grande do Sul      19
Bahia                  17
Goiás                  15
Pará                   15
Santa Catarina         14
Pernambuco             12
Maranhão               10
Espírito Santo          9
Ceará                   7
Mato Grosso             6
Paraíba                 4
Rio Grande do Norte     4
Sergipe                 4
Mato Grosso do Sul      3
Alagoas                 2
Piauí                   2
Rondônia                2
Amapá                   2
Tocantins               2
Amazonas                2
Roraima                 1
Acre                    1
Name: count, dtype: int64

In [72]:
dados_populacao_reduzido.iloc[(dados_populacao_reduzido['ranking'] < 20) | (dados_populacao_reduzido['uf'] == 'São Paulo')]
dados_populacao_reduzido

     ranking     municipio                 uf  populacao  dentro_da_faixa
7          8      Curitiba             Paraná    1773718             True
8          9        Recife         Pernambuco    1488920             True
9         10       Goiânia              Goiás    1437366             True
10        11  Porto Alegre  Rio Grande do Sul    1332845             True
11        12         Belém               Pará    1303403             True
..       ...           ...                ...        ...              ...
314      315    Manacapuru           Amazonas     101883             True
315      316        Balsas           Maranhão     101767             True
316      317       Lagarto            Sergipe     101579             True
317      318         Assis          São Paulo     101409             True
318      319     Itaperuna     Rio de Janeiro     101041             True

[312 rows x 5 columns]

In [76]:
dados_populacao_reduzido.describe()

          ranking     populacao
count  312.000000  3.120000e+02
mean   163.496795  2.754413e+05
std     90.206801  2.480127e+05
min      8.000000  1.010410e+05
25%     85.750000  1.260385e+05
50%    163.500000  1.830035e+05
75%    241.250000  3.266708e+05
max    319.000000  1.773718e+06