In [2]:
import pandas as pd

df_csv = pd.read_csv('python-diferentes-formatos-dados/cidades.csv')
df_csv.head()

   ranking       municipio                uf   populacao
0        1       São Paulo         São Paulo  11 451 999
1        2  Rio de Janeiro    Rio de Janeiro   6 211 223
2        3        Brasília  Distrito Federal   2 817 381
3        4       Fortaleza             Ceará   2 428 708
4        5        Salvador             Bahia   2 417 678

In [5]:
df_hash_csv = pd.read_csv('python-diferentes-formatos-dados/cidades_separado_por_hashtag.csv', sep='#', header=None)
df_hash_csv.head()

         0               1                 2           3
0  ranking       municipio                uf   populacao
1        1       São Paulo         São Paulo  11 451 999
2        2  Rio de Janeiro    Rio de Janeiro   6 211 223
3        3        Brasília  Distrito Federal   2 817 381
4        4       Fortaleza             Ceará   2 428 708

In [6]:
df_hash_csv.to_csv('csv_salvo.csv')

In [2]:
import pandas as pd

df_excel = pd.read_excel('python-diferentes-formatos-dados/cidades.xlsx', 'Populacao')
df_excel.head()

   ranking       municipio                uf   populacao
0        1       São Paulo         São Paulo  11 451 999
1        2  Rio de Janeiro    Rio de Janeiro   6 211 223
2        3        Brasília  Distrito Federal   2 817 381
3        4       Fortaleza             Ceará   2 428 708
4        5        Salvador             Bahia   2 417 678

In [5]:
df_excel.to_excel('excel.xlsx', index=False)

In [6]:
df_json = pd.read_json('python-diferentes-formatos-dados/cidades.json')
df_json.head()

   ranking       municipio                uf   populacao
0        1       São Paulo         São Paulo  11 451 999
1        2  Rio de Janeiro    Rio de Janeiro   6 211 223
2        3        Brasília  Distrito Federal   2 817 381
3        4       Fortaleza             Ceará   2 428 708
4        5        Salvador             Bahia   2 417 678

In [9]:
df_json.to_json('meu.json', indent=4, orient='records')

In [10]:
df_xml = pd.read_xml('python-diferentes-formatos-dados/cidades.xml')
df_xml.head()

   ranking       municipio                uf   populacao
0        1       São Paulo         São Paulo  11 451 999
1        2  Rio de Janeiro    Rio de Janeiro   6 211 223
2        3        Brasília  Distrito Federal   2 817 381
3        4       Fortaleza             Ceará   2 428 708
4        5        Salvador             Bahia   2 417 678

In [11]:
df_xml.to_xml('meu.xml')

In [42]:
df_html = pd.read_html('https://pt.wikipedia.org/wiki/Lista_de_mucic%C3%ADpios_do_Brasil_acima_de_cem_mil_habitantes_(2022)')
df_html[0].head()

HTTPError: HTTP Error 403: Forbidden

In [27]:
df_html[0].to_html('meu.html'